# ==================================================
# 🚀 MARAV - CONFIGURACIÓN DE LA APLICACIÓN
# ==================================================

spring.application.name=MARAV


# ==================================================
# 🗄 BASE DE DATOS MYSQL
# ==================================================
#
# Durante el desarrollo seguimos utilizando MySQL
# instalado en nuestro computador.
#
# IMPORTANTE:
# En producción estos valores se proporcionarán
# mediante variables de entorno.
# ==================================================

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/eco_market?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ==================================================
# 🔥 JPA / HIBERNATE
# ==================================================

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}

# Durante desarrollo podemos ver las consultas.
# Más adelante en producción lo cambiaremos a false.
spring.jpa.show-sql=${SHOW_SQL:true}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=${FORMAT_SQL:true}


# ==================================================
# 📧 CORREO GMAIL
# ==================================================
#
# IMPORTANTE:
# La contraseña NO debe quedar escrita directamente
# en este archivo.
#
# Se utilizará una variable de entorno.
# ==================================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${MAIL_USERNAME:MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# ==================================================
# ⏱ TIMEOUTS DEL CORREO
# ==================================================

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

server.port=${PORT:8080}